### ISSUE TITLE
Duplicate markers on the map.

### ISSUE THREAD

**Issue by barkovskiy** [eregnier/vue2-gmap-custom-marker#38]
Hello! I have problem with duplicate markers on the map.

My code very simple.
`<GmapMap ref="gmap" :center="center" :zoom="zoom" style="width: 100%; height: 100%">
<cluster>
          <gmap-custom-marker
            v-for="marker in markers"
            v-bind:key="marker.id"
            :marker="marker.pos"
          >...<gmap-custom-marker></cluster></GmapMap>`

I tryed to add check for marker existence (check by **isAdded** props in **inst** object) in **afterCreate** function and this fix my trouble. 

Can you add this check in code or do you have some explanations why I have duplicates?

Thank you in advance.

**Comment by eregnier** [comment]
I have not enough clues with your code sample. 
I guess your issue comes from markers data. You may check this content and find out why is there some duplicate markers.
I also may help more if you share me some shareable markers data. (you may share the whole annonymised for exemple.

I have no other issues like this until now and there are now quite some user using this plugin. I doubt this issue comes from this plugin, however if we find where does it comes from and in case this issue is related this plugin code, I'd be happy to fix it.

Let me know if you still need help on this topic.

**Comment by barkovskiy** [comment]
@eregnier 

Markers come from backend and has unique id. Marker example:
`{"id":6,"lat":55.6668532,"lng":37.2757566}`

I added check for marker existence (check by isAdded props in inst object) in afterCreate function and this fix my trouble with duplicates, but i received next error:
`DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

This error appears only when an array with markers comes from the backend, and some of the past markers are missing from it.

Marker code:
```
<gmap-custom-marker
     v-for="marker in markers"
     v-bind:key="marker.id"
     :marker="marker.pos"
     @click.native="event => showFacility(marker.id, event)"
     @mouseover.native="receiveFacility(marker.id)"
     :z-index="marker.id === selectedMarkerId ? 50 : 10"
>
     <div class="map-marker">
          <div class="icon">
               <img src="/img/building.png" />
          </div>
          <div class="body" v-if="marker.id === selectedMarkerId">
              ...
          </div>
     </div>
</gmap-custom-marker>
```

**Comment by eregnier** [comment]
try to wrap your custom markers into a div if you have many sibbling custom marker. This prevent vue to loose track of your components. 

Let me know if this solved your issue.

**Comment by eregnier** [comment]
@barkovskiy any news ? If no I will close soon.

**Comment by eregnier** [comment]
close due to inactivity.
