### ISSUE TITLE
Can not using gmap custom maker in nuxt 2.0 typescript

### ISSUE THREAD

**Issue by thanhchuongbmd** [eregnier/vue2-gmap-custom-marker#47]
> Package version ^6.0.0

Version 5.6.2 working ok!
In my nuxt config: 
`{
 build: {
    transpile: [
      /^element-ui/,
      /^vue2-google-maps($|\/)/,
      "vue2-gmap-custom-marker"
    ]
  }
}
`
<img width="1358" alt="Screen Shot 2020-11-30 at 11 14 20" src="https://user-images.githubusercontent.com/67777599/100568765-abc79d80-32fe-11eb-936f-3701b856d3cf.png">

**Comment by eregnier** [comment]
Hey, 
This issue is because I changed the underlying gmap vue library. see [the note](https://github.com/eregnier/vue2-gmap-custom-marker#-important-note) for more information. 
You can either :
 - upgrade to maintained library 
 - stick to the legacy library

Let me know if there is any other troubles.
