### ISSUE TITLE
cannot redraw marker when marker's prop change

### ISSUE THREAD

**Issue by athasamid** [eregnier/vue2-gmap-custom-marker#5]
why cannot redraw/update marker when marker data change?

**Comment by eregnier** [comment]
it seems that it works properly when I try it. I did a demo there https://eregnier.github.io/vue2-gmap-custom-marker/dist/ that is commited in the gh-pages branch where you can see the code.

**Comment by eregnier** [comment]
I modified the code, the plugin is now in V4.0 and let the user dom content to really live within each marker and it is possible to manage data binding and such like in the demo. I just found a way to use the user dom instead of cold copy that previously was breaking data bindings and events listeners.

Checkout out the demo et let me know if this is ok for you.

**Comment by athasamid** [comment]
Thanks, You save my day

**Comment by eregnier** [comment]
I spend all my night on it, but the plugin is now way better :D
Glad I saved you day !
