### ISSUE TITLE
How to drag the marker?

### ISSUE THREAD

**Issue by vinayakkulkarni** [eregnier/vue2-gmap-custom-marker#53]
There's a draggable prop & dragend event for the default gmap-marker in the other repo, there's no example of draggable or dragend for markers using this lib ?

https://github.com/eregnier/vue2-gmap-custom-marker/blob/master/gmap-custom-marker.vue#L152

:O

**Comment by eregnier** [comment]
There is no exemple because this is not implemented at all. 
I don't know how It should be done. 
I guess we can implement the same logic than the core library marker.
I don't know however where to start for now. I have to find time to study this case and find a solution.
Feel free to PR for this, it will be surely accepted if it works ;)

Thank you for suggesting.

**Comment by eregnier** [comment]
close due to inactivity.
