### ISSUE TITLE
Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by ColossalPercy** [eregnier/vue2-gmap-custom-marker#6]
Just updated to v5.0.1 to stop the flickering of icons, works perfectly so thank you for that.

However, I'm now getting an error that did not occur when on v3.0.2:
`[Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."`

Part of my code includes filtering the icons that are on the map. When I update this filter I get the above error thrown. Presumably is therefore an issue with removing and adding custom markers.

Thanks for any help and let me know if you need to see some code.

**Comment by eregnier** [comment]
I think i had this issue before. This is vue dom management related. I wrapped my custom markers into an extra div within the map tag to solve the issue. This is because i think vue js does not succeed with generation looped content with slots  dom content. On my side i dont know how what to do to handle this but i should try to wrap my slot tag of the component template into an extra div. I have to find a reproducible code to test it.

**Comment by eregnier** [comment]
I forgot that there is already a wrapping div in the component. I do not succeed in reproducing the error (maybe it is a good thing) so, you may just wrap the custom markers components in a div. Let me know if this works. As I told you, the problem may be that you do a v-for on the component directly and so vuejs does not manage this properly. Let me know if the wrapping div solves the issue.

This is I think a sibbling node issue. the dom in the v5x is simply binded to the marker dom and so it is managed by your filter directly and no more inside the component.

**Comment by ColossalPercy** [comment]
Apologies, after a PC shutdown the error has gone, must have been a strange caching issue.

When I apply the filter there is no issue, but as I remove the filter and the markers start to re-appear I get an error:

`gmap-custom-marker.vue?ad03:55 Uncaught (in promise) TypeError: Cannot read property 'offsetWidth' of undefined
    at Overlay.draw (gmap-custom-marker.vue?ad03:55)
    at eval `(gmap-custom-marker.vue?ad03:13)`

This doesn't cause an actual issue in the app, just the error in the console.
Live demo: https://colossalpercy.github.io/reninsane/map/
Source: https://github.com/ColossalPercy/reninsane-viewer-map/blob/master/src/components/TheMap.vue

**Comment by eregnier** [comment]
Thank you for your time providing a reproducable bug project.
I checked out your code and it appears that in the new version of the component, the remove dom management is not well implemented. I will fix this asap to make it work properly.
This issue is mainly related to the fact that in the new version the dom is shared from container parent to child whereas it was previously a dom copy and clean was properly implmented for this version.

**Comment by eregnier** [comment]
I solved the bug. https://github.com/eregnier/vue2-gmap-custom-marker/commit/6cb1999ba41e166dfb77510d0405fdfc042ad2d6

it seems to fix the bug in for your project.

Is it ok on your side ?

**Comment by ColossalPercy** [comment]
Fixed. That's perfect thanks.
